const drafts: Draft[] = [
  { id: 1, name: "Draft 1" },
  { id: 2, name: "Draft 2" },
  { id: 3, name: "Draft 3" },
  { id: 4, name: "Draft 4" },
  { id: 5, name: "Draft 5" },
  { id: 6, name: "Draft 6" },
  { id: 7, name: "Draft 7" },
  { id: 8, name: "Draft 8" },
  { id: 9, name: "Draft 9" },
  { id: 10, name: "Draft 10" },
  // Add more drafts as needed
];

const projects: Project[] = [
  {
    id: 1,
    name: "Project 1",
    description: "This is a sample project",
    labels: ["label1", "label2"],
    state: 'in progress',
  },
  {
    id: 2,
    name: "Project 2",
    description: "Another sample project",
    labels: ["label3", "label4"],
    state: 'done',
  },
  {
    id: 3,
    name: "Project 3",
    description: "A third project",
    labels: ["label5"],
    state: 'on hold',
  },
  {
    id: 4,
    name: "Project 4",
    description: "Yet another project",
    labels: ["label6", "label7"],
    state: 'in progress',
  },
  {
    id: 5,
    name: "Project 5",
    description: "Project with multiple labels",
    labels: ["label8", "label9", "label10"],
    state: 'canceled',
  },
  {
    id: 6,
    name: "Project 6",
    description: "Project with a long description",
    labels: ["label11"],
    state: 'done',
  },
  {
    id: 7,
    name: "Project 7",
    description: "Project with no labels",
    labels: [],
    state: 'in progress',
  },
  {
    id: 8,
    name: "Project 8",
    description: "Project with an interesting description",
    labels: ["label12"],
    state: 'canceled',
  },
  {
    id: 9,
    name: "Project 9",
    description: "Project in an undecided state",
    labels: ["label13"],
    state: 'on hold',
  },
  {
    id: 10,
    name: "Project 10",
    description: "Project with a simple description",
    labels: ["label14"],
    state: 'done',
  },
  // Add more projects as needed
];

const tasks: Task[] = [
  { id: 1, project_id: 1, name: "Task 1", state: 'in progress' },
  { id: 2, project_id: 2, name: "Task 2", state: 'done' },
  { id: 3, project_id: 3, name: "Task 3", state: 'on hold' },
  { id: 4, project_id: 4, name: "Task 4", state: 'in progress' },
  { id: 5, project_id: 5, name: "Task 5", state: 'canceled' },
  { id: 6, project_id: 6, name: "Task 6", state: 'done' },
  { id: 7, project_id: 7, name: "Task 7", state: 'in progress' },
  { id: 8, project_id: 8, name: "Task 8", state: 'canceled' },
  { id: 9, project_id: 9, name: "Task 9", state: 'on hold' },
  { id: 10, project_id: 10, name: "Task 10", state: 'done' },
  { id: 11, project_id: 3, name: "Task 11", state: 'in progress' },
  { id: 12, project_id: 4, name: "Task 12", state: 'done' },
  { id: 13, project_id: 5, name: "Task 13", state: 'on hold' },
  { id: 14, project_id: 6, name: "Task 14", state: 'in progress' },
  { id: 15, project_id: 7, name: "Task 15", state: 'canceled' },
  { id: 16, project_id: 8, name: "Task 16", state: 'done' },
  { id: 17, project_id: 9, name: "Task 17", state: 'in progress' },
  { id: 18, project_id: 10, name: "Task 18", state: 'canceled' },
  { id: 19, project_id: 1, name: "Task 19", state: 'on hold' },
  { id: 20, project_id: 2, name: "Task 20", state: 'done' },
  { id: 21, project_id: 4, name: "Task 21", state: 'in progress' },
  { id: 22, project_id: 5, name: "Task 22", state: 'done' },
  { id: 23, project_id: 6, name: "Task 23", state: 'on hold' },
  { id: 24, project_id: 7, name: "Task 24", state: 'in progress' },
  { id: 25, project_id: 8, name: "Task 25", state: 'canceled' },
  { id: 26, project_id: 9, name: "Task 26", state: 'done' },
  { id: 27, project_id: 10, name: "Task 27", state: 'in progress' },
  { id: 28, project_id: 1, name: "Task 28", state: 'canceled' },
  { id: 29, project_id: 2, name: "Task 29", state: 'on hold' },
  { id: 30, project_id: 3, name: "Task 30", state: 'done' },
].map(task => ({
  ...task,
  description: `Description for Task ${task.id}`,
}));

export default { drafts, projects, tasks };
